eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://admin:examplePassword@localhost:18091/eureka/}

spring:
  application:
    name: 6-sixth-service

server:
  port: ${SERVICE_PORT:0}