eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:examplePassword@localhost:18091/eureka/


spring:
  application:
    name: 11-eleventh-service
  kafka:
    bootstrapServers: localhost:29092

    producer:
      clientId: ${spring.application.name}
#      keySerializer: org.apache.kafka.common.serialization.StringSerializer
      valueSerializer: joh.faust.stream.data.RandomValueSerializer

    consumer:
      clientId: ${spring.application.name}
      groupId: ${spring.application.name}-group
#      keyDeserializer: org.apache.kafka.common.serialization.StringDeserializer
      valueDeserializer: joh.faust.stream.data.RandomValueDeserializer
      auto-offset-reset: earliest

    streams:
      clientId: ${spring.application.name}-stream
      applicationId: ${spring.application.name}
      properties:
        default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        default.value.serde: joh.faust.stream.data.RandomValueSerde

server:
  port: 0