eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://admin:examplePassword@localhost:18091/eureka/}
  instance:
    preferIpAddress: true


spring:
  application:
    name: 12-twelfth-service
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
  cache:
    redis:
      time-to-live: 5000
      cache-null-values: false

server:
  port: ${SERVICE_PORT:0}