apiVersion: apps/v1
kind: Deployment
metadata:
  name: fifteenth-deployment
  labels:
    app: fifteenth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fifteenth
  template:
    metadata:
      labels:
        app: fifteenth
    spec:
      containers:
        - name: fifteenth
          image: fifteenth-local:latest
          imagePullPolicy: Never
          env:
            - name: SERVICE_PORT
              value: "14015"
            - name: EUREKA_URL
              value: "http://admin:examplePassword@discovery-service:8091/eureka/"
          ports:
            - containerPort: 14015