apiVersion: v1
kind: Service
metadata:
  name: third-service
spec:
  selector:
    app: third
  ports:
    - name: service
      protocol: TCP
      port: 4003
      targetPort: 14003
    - name: actuator
      protocol: TCP
      port: 9876
      targetPort: 9876