services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      - JAEGER_DISABLED=true
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 4318:4318
      - 16686:16686
      - 14268:14268
      - 14250:14268

  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: docker.io/bitnami/kafka:3.4
    ports:
      - "29092:29092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ENABLE_KRAFT=no
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:29092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:29092
    depends_on:
      - zookeeper

  postgres:
    container_name: keycloak_db
    image: postgres
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
      POSTGRES_DB: keycloak
    volumes:
      - 'pgsql_data:/var/lib/postgresql/data'
  keycloak:
    hostname: keycloak
    container_name: keycloak
    image: bitnami/keycloak:latest
    environment:
      KEYCLOAK_ADMIN_USER: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_MANAGEMENT_USER: manager
      KEYCLOAK_MANAGEMENT_PASSWORD: manager
      KEYCLOAK_DATABASE_HOST: keycloak_db
      KEYCLOAK_DATABASE_NAME: keycloak
      KEYCLOAK_DATABASE_USER: keycloak
      KEYCLOAK_DATABASE_PASSWORD: keycloak
      KEYCLOAK_EXTRA_ARGS: --hostname keycloak
    entrypoint: /bin/bash -c
    command:
      - /opt/bitnami/keycloak/bin/kc.sh import --file=/opt/keycloak/data/import/realm.json --override true 2>/dev/null && /opt/bitnami/scripts/keycloak/run.sh --verbose
    ports:
      - "8080:8080"
    healthcheck:
      test: curl --head -fsS http://localhost:8080
      interval: 60s
      retries: 1000
      start_period: 20s
      timeout: 10s
    depends_on:
      - postgres
    volumes:
      - type: bind
        source: ./keycloak/realms
        target: /opt/keycloak/data/import

  discovery:
    image: discovery-local:latest
    expose:
      - 18091
    ports:
      - 18091:18091
    depends_on:
      jaeger:
        condition: service_started
      kafka:
        condition: service_started
      keycloak:
        condition: service_healthy

  configuration-server:
    image: configuration-server-local:latest
    environment:
      SERVICE_PORT: 8012
      KAFKA_HOSTNAME: kafka
      KAFKA_PORT: 29092
      GIT_URI: https://github.com/JohannFaustVIII/SCPConfiguration
      DEFAULT_LABEL: docker
    expose:
      - 8012
    depends_on:
      - kafka

  first:
    image: first-local
    environment:
      SERVICE_PORT: 14001
      EUREKA_URL: http://admin:examplePassword@discovery:18091/eureka/
    expose:
      - 14001
    ports:
      - 14001:14001
    depends_on:
      - discovery

  gateway:
    image: gateway-local:latest
    environment:
      SERVICE_PORT: 8081
      EUREKA_URL: http://admin:examplePassword@discovery:18091/eureka/
      KEYCLOAK_URL: http://keycloak:8080/realms/SRealm
    expose:
      - 8081
    ports:
      - 8081:8081
    depends_on:
      discovery:
        condition: service_started
      keycloak:
        condition: service_healthy
      first:
        condition: service_started

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
  pgsql_data:
    driver: local