apiVersion: v1
kind: ConfigMap
metadata:
  name: oauth2-proxy-config
data:
  oauth2-proxy.cfg: |-
    # Provider config
    provider="keycloak"
    provider_display_name="Keycloak"
    login_url="http://keycloak.server.com/realms/SRealm/protocol/openid-connect/auth"
    redeem_url="http://keycloak.server.com/realms/SRealm/protocol/openid-connect/token"
    validate_url="http://keycloak.server.com/realms/SRealm/protocol/openid-connect/userinfo"
    profile_url="http://keycloak.server.com/realms/SRealm/protocol/openid-connect/userinfo"
    ssl_insecure_skip_verify=true
    # Client config
    client_id="gateway-client"
    client_secret="XuP788Es8CYur4FGG84hf5PfEnnaMZR8"
    cookie_secret="ZzBkN000Wm0pQkVkKUhzMk5YPntQRUw_ME1oMTZZTy0="
    cookie_secure="false"
    # Upstream config
    http_address="0.0.0.0:4180"
    upstreams="file:///dev/null"
    email_domains=["*"]
    oidc_issuer_url="http://keycloak.server.com/realms/SRealm"
    cookie_domains=["*"]
    scope="openid"
    whitelist_domains=["*"]