apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth2-deployment
  labels:
    app: oauth2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauth2
  template:
    metadata:
      labels:
        app: oauth2
    spec:
      containers:
        - name: oauth2-proxy
          image: quay.io/oauth2-proxy/oauth2-proxy:latest
          ports:
            - containerPort: 4180
          args: ['--config=/etc/oauth2-proxy.cfg']
          volumeMounts:
            - name: oauth2-proxy-config
              mountPath: '/etc/oauth2-proxy.cfg'
              subPath: 'oauth2-proxy.cfg'
      volumes:
        - name: oauth2-proxy-config
          configMap:
            name: oauth2-proxy-config