eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://admin:examplePassword@localhost:18091/eureka/}
  instance:
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  otlp:
    tracing:
      endpoint: ${JAEGER_ENDPOINT:http://localhost:4318/v1/traces}
  tracing:
    enabled: true
    sampling:
      probability: 1.0

logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'

spring:
  application:
    name: 9-ninth-service
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
        alphanumeric-ids:
          enabled: true
      micrometer:
        enabled: true

resilience4j:
  circuitbreaker:
    instances:
      EightApiClientgetIntegers:
        minimumNumberOfCalls: 4
        failureRateThreshold: 25
  timelimiter:
    instances:
      EightApiClientgetIntegers:
        timeoutDuration: 2s

server:
  port: ${SERVICE_PORT:0}