eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://admin:examplePassword@localhost:18091/eureka/}
  instance:
    preferIpAddress: true


spring:
  application:
    name: 13-thirteenth-service
  datasource:
    url: jdbc:h2:file:./database
  h2:
    console:
      enabled: true
      path: /console
  jpa:
    hibernate:
      ddlAuto: validate


server:
  port: ${SERVICE_PORT:0}