apiVersion: apps/v1
kind: Deployment
metadata:
  name: thirteenth-deployment
  labels:
    app: thirteenth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thirteenth
  template:
    metadata:
      labels:
        app: thirteenth
    spec:
      containers:
        - name: thirteenth
          image: thirteenth-local:latest
          imagePullPolicy: Never
          env:
            - name: SERVICE_PORT
              value: "14013"
            - name: EUREKA_URL
              value: "http://admin:examplePassword@discovery-service:8091/eureka/"
          ports:
            - containerPort: 14013