services:
  jaeger-allinone:
    image: jaegertracing/all-in-one:latest
    environment:
      - JAEGER_DISABLED=true
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 4318:4318
      - 16686:16686
      - 14268:14268
      - 14250:14268