apiVersion: v1
kind: Service
metadata:
  name: jaeger-service
spec:
  selector:
    app: jaeger
  ports:
    - name: service
      protocol: TCP
      port: 4318
      targetPort: 4318
    - name: gui
      protocol: TCP
      port: 16686
      targetPort: 16686