spring:
  application:
    name: configuration-server
  cloud:
    config:
      server:
        git:
          uri: ${GIT_URI:https://github.com/JohannFaustVIII/SCPConfiguration}
          cloneOnStart: true
          defaultLabel: ${DEFAULT_LABEL:main}
    bus:
      enabled: true
  kafka:
    bootstrapServers: ${KAFKA_HOSTNAME:localhost}:${KAFKA_PORT:29092}

server:
  port: ${SERVICE_PORT:8012}