server:
  port: ${SERVICE_PORT:8081}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://admin:examplePassword@localhost:18091/eureka/}
  instance:
    preferIpAddress: true

spring:
  application:
    name: gateway
  security:
    oauth2:
      client:
        provider:
          my-keycloak-provider:
            issuer-uri: ${KEYCLOAK_URL:http://localhost:8180/realms/SRealm}
        registration:
          keycloak-client:
            provider: my-keycloak-provider
            client-id: ${KEYCLOAK_CLIENT_ID:gateway-client}
            client-secret: ${KEYCLOAK_CLIENT_SECRET:XuP788Es8CYur4FGG84hf5PfEnnaMZR8}
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/login/oauth2/code/keycloak'
            scope: openid
  cloud:
    gateway:
      routes:
        - id: eureka
          uri: ${EUREKA_ROUTE_URL:http://localhost:18091}
          predicates:
            - Path=/discovery/**
          filters:
            - RewritePath=/discovery(?<remaining>/?.*), /$\{remaining}
        - id: eureka_resources
          uri: ${EUREKA_ROUTE_URL:http://localhost:18091}
          predicates:
            - Path=/eureka/**
        - id: firstService
          uri: lb://1-first-service
          predicates:
            - Path=/first/**
          filters:
            - StripPrefix=1
        - id: secondService
          uri: lb://2-second-service
          predicates:
            - Path=/second/**
          filters:
            - StripPrefix=1
        - id: thirdService
          uri: lb://3-third-service
          predicates:
            - Path=/third/**
          filters:
            - StripPrefix=1
        - id: fourthService
          uri: lb://4-fourth-service
          predicates:
            - Path=/fourth/**
          filters:
            - StripPrefix=1
        - id: fifthService
          uri: lb://5-fifth-service
          predicates:
            - Path=/fifth/**
          filters:
            - StripPrefix=1
        - id: sixthService
          uri: lb://6-sixth-service
          predicates:
            - Path=/sixth/**
          filters:
            - StripPrefix=1
        - id: seventhService
          uri: lb://7-seventh-service
          predicates:
            - Path=/seventh/**
          filters:
            - StripPrefix=1
            - TokenRelay=
        - id: eighthService
          uri: lb://8-eighth-service
          predicates:
            - Path=/eighth/**
          filters:
            - StripPrefix=1
        - id: ninthService
          uri: lb://9-ninth-service
          predicates:
            - Path=/ninth/**
          filters:
            - StripPrefix=1
        - id: tenthService
          uri: lb://10-tenth-service
          predicates:
            - Path=/tenth/**
          filters:
            - StripPrefix=1
        - id: twelfthService
          uri: lb://12-twelfth-service
          predicates:
            - Path=/twelfth/**
          filters:
            - StripPrefix=1