server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:18091/eureka/

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: firstService
          uri: lb://first-service
          predicates:
            - Path=/first/**
          filters:
            - StripPrefix=1
        - id: secondService
          uri: lb://second-service
          predicates:
            - Path=/second/**
          filters:
            - StripPrefix=1
        - id: thirdService
          uri: lb://third-service
          predicates:
            - Path=/third/**
          filters:
            - StripPrefix=1
        - id: fourthService
          uri: lb://fourth-service
          predicates:
            - Path=/fourth/**
          filters:
            - StripPrefix=1
        - id: fifthService
          uri: lb://fifth-service
          predicates:
            - Path=/fifth/**
          filters:
            - StripPrefix=1
        - id: sixthService
          uri: lb://sixth-service
          predicates:
            - Path=/sixth/**
          filters:
            - StripPrefix=1