services:
  postgres:
    container_name: keycloak_db
    image: postgres
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
      POSTGRES_DB: keycloak
    volumes:
      - 'pgsql_data:/var/lib/postgresql/data'

  keycloak:
    container_name: keycloak_for_services
    image: bitnami/keycloak:latest
    environment:
      KEYCLOAK_ADMIN_USER: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_MANAGEMENT_USER: manager
      KEYCLOAK_MANAGEMENT_PASSWORD: manager
      KEYCLOAK_DATABASE_HOST: keycloak_db
      KEYCLOAK_DATABASE_NAME: keycloak
      KEYCLOAK_DATABASE_USER: keycloak
      KEYCLOAK_DATABASE_PASSWORD: keycloak
    entrypoint: /bin/bash -c
    command:
      - /opt/bitnami/keycloak/bin/kc.sh import --file=/opt/keycloak/data/import/realm.json --override true 2>/dev/null && /opt/bitnami/scripts/keycloak/run.sh --verbose
    healthcheck:
      test: curl --head -fsS http://localhost:8080
      interval: 60s
      retries: 1000
      start_period: 20s
      timeout: 10s
    ports:
      - "8180:8080"
    depends_on:
      - postgres
    volumes:
      - type: bind
        source: ./realms
        target: /opt/keycloak/data/import

volumes:
  pgsql_data:
    driver: local