eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://admin:examplePassword@localhost:18091/eureka/}
  instance:
    preferIpAddress: true

spring:
  application:
    name: 5-fifth-service

server:
  port: ${SERVICE_PORT:0}

sixService:
  name: ${SIX_SERVICE_NAME:6-sixth-service}