eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:examplePassword@localhost:18091/eureka/
  instance:
    instanceId: ${random.value}


spring:
  application:
    name: 1-first-service

server:
  port: 0