eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://admin:examplePassword@localhost:18091/eureka/}
  instance:
    instanceId: ${random.value}
    preferIpAddress: true


spring:
  application:
    name: 1-first-service

server:
  port: ${SERVICE_PORT:0}