spring:
  application:
    name: 2-second-service
  config:
    import: configserver:${CONFIG_SERVER_URL:http://localhost:8012}
  cloud:
    bus:
      enabled: true
      id: ${spring.application.name}:${random.uuid}
      refresh:
        enabled: true
      env:
        enabled: true
    config:
      failFast: true
  kafka:
    bootstrapServers: ${KAFKA_HOSTNAME:localhost}:${KAFKA_PORT:29092}

server:
  port: ${SERVICE_PORT:0}

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh, bus-env