apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-simple
spec:
  rules:
    - host: discovery.server.com
      http:
        paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: discovery-service
              port:
                number: 8091