server:
  port: 18091

eureka:
  client:
    fetchRegistry: false
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://admin:examplePassword@localhost:18091/eureka/

spring:
  security:
    user:
      name: admin
      password: examplePassword