eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:examplePassword@localhost:18091/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'
  otlp:
    tracing:
      endpoint: localhost:4318/v1/traces
  tracing:
    sampling:
      probability: 1.0

spring:
  application:
    name: 10-tenth-service

server:
  port: 0

