eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://admin:examplePassword@localhost:18091/eureka/}
  instance:
    preferIpAddress: true


spring:
  application:
    name: 14-fourteenth-service
  datasource:
    url: jdbc:h2:file:./fourteenth
  h2:
    console:
      enabled: true
      path: /console
      settings:
        webAllowOthers: true
  jpa:
    hibernate:
      ddlAuto: create-only


server:
  port: ${SERVICE_PORT:0}