apiVersion: apps/v1
kind: Deployment
metadata:
  name: second-deployment
  labels:
    app: second
spec:
  replicas: 1
  selector:
    matchLabels:
      app: second
  template:
    metadata:
      labels:
        app: second
    spec:
      containers:
        - name: second
          image: second-local:latest
          imagePullPolicy: Never
          env:
            - name: SERVICE_PORT
              value: "14002"
            - name: KAFKA_HOSTNAME
              value: "kafka-service"
            - name: KAFKA_PORT
              value: "29092"
            - name: CONFIG_SERVER_URL
              value: "http://configuration-service:8012"
          ports:
            - containerPort: 14002