eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://admin:examplePassword@localhost:18091/eureka/}
  instance:
    preferIpAddress: true

spring:
  application:
    name: 7-seventh-service
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWK_URI:http://localhost:8180/realms/SRealm/protocol/openid-connect/certs}

server:
  port: ${SERVICE_PORT:0}